;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-newline-and-maybe-indent
        end-of-buffer
        ivy-switch-buffer
        keyboard-escape-quit
        markdown-follow-link-at-point
        markdown-outdent-or-delete
        paredit-semicolon
        smex
        ))

(setq mc/cmds-to-run-once
      '(
        ))
